name: rust
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo test --all-features
      - run: cargo clippy --all-features --all-targets -- --deny warnings
      - run: cargo build --all-features
      - uses: actions/upload-artifact@v3
        with:
          name: release-${{ matrix.os }}
          path: target/release/ff*
